#ifndef __CarInfoAndAffair_H__
#define __CarInfoAndAffair_H__

void SetG_Urgent_Car_Team_Enabled(BOOL  value);
int GetG_Urgent_Car_Team_Enabled(void);
void AddG_Car_Pass_Count(void);
int GetG_Car_Pass_Count(void);
void AddG_Car_Passed_Count(void);
int GetG_Car_Passed_Count(void);
void SetG_Max_Show_Car_Pass_Count(int  value);
int GetG_Max_Show_Car_Pass_Count(void);
void SetG_Show_Car_Tem_Index(int  value);
int GetG_Show_Car_Tem_Index(void);

void SetG_Car_Pass_Count(int value);
void SetG_Car_Passed_Count(int value);
void AddG_Show_Car_Tem_Index(void);
void DesG_Show_Car_Tem_Index(void);
void AddG_reprintbillnum(void);
void SetG_weiZhangState(int value);
int GetG_weiZhangState(void);
void SetG_weiZhangType(int value);
int GetG_weiZhangType(void);
void SetG_simulateType(int value);
int GetG_simulateType(void);
void SetG_simulateEnabled(BOOL  value);
int GetG_simulateEnabled(void);
void SetG_simulateWorkState(int  value);
int GetG_simulateWorkState(void);
void SetG_billRePrintEnabled(BOOL  value);
int GetG_billRePrintEnabled(void);
void SetG_reprintbillnum(int  value);
int GetG_reprintbillnum(void);
void SetbillNumber_str(char * value);
void SetG_Loop_Enable(BOOL  value);
int GetG_Loop_Enable(void);
void SetcarTem(int value);
int GetcarTem(void);
void SetG_Car_Team_Enabled(BOOL  value);
int GetG_Car_Team_Enabled(void);
void SetG_CarNumber(char *value);
char *GetG_CarNumber(void);
void SetG_BeforWzWorkstation(int  value);
int GetG_BeforWzWorkstation(void);
void SetG_BeforWzLaneState(int  value);
int GetG_BeforWzLaneState(void);
void SetG_BillPrintFlag(int value);
int GetG_BillPrintFlag(void);
void SetG_ArrearageNumber(char *value);
char *GetG_ArrearageNumber(void);
void SetG_ArrearageCharge(int  value);
int GetG_ArrearageCharge(void);
void SetG_ArrearageChargeChar(char  *value);
char *GetG_ArrearageChargeChar(void);
void SetinCarTeamOtherCar(BOOL   value);
BOOL  GetinCarTeamOtherCar(void);
void SetG_Current_Handl_Car_Type(char  *value);
char *GetG_Current_Handl_Car_Type(void);
int Get_Current_Car_Type_Index(void);
void SetG_Current_Handl_Car_Kind(char  *value);
char *GetG_Current_Handl_Car_Kind(void);
void SetG_Current_Handl_Car_Kind_INT(int value);
int GetG_Current_Handl_Car_Kind_INT(void);
void SetG_Current_Handl_Charge(float value);
float GetG_Current_Handl_Charge(void);
char * GetG_Current_Handl_Charge_str(void);
void SetG_Current_Car_Team_Charge_Total(int  value);
int GetG_Current_Car_Team_Charge_Total(void);
void SetG_Show_Handl_Car_Information(char  *value);
char *GetG_Show_Handl_Car_Information(void);
void SetG_Car_Type(char* value);
char *GetG_Car_Type(void);
void SendTcoWaingMsg(char *Msg);
void InitG_Show_Handl_Car_Information(void);
void strcatG_Show_Handl_Car_Information(char * value);
void InitG_Current_Handl_Car_Kind(void);
void InitG_Current_Handl_Car_Type(void);
void InitG_Car_Type(void);
void  InitG_CarNumber(void);
void  InitG_ArrearageNumber(void);
void InitG_ArrearageChargeChar(void);
void  SETG_ArrearageNumber_end(int  value);
void  SETG_ArrearageChargeChar_end(int  value);
void SETG_Car_Type_end(int  value);
void  SETG_CarNumber_end(int  value);
 void Delete_Handl_Car_Information(int index);
void DesG_Car_Pass_Count(void);
char * GetbillNumber_str(void);
void InitYCQK(void);
void AddYCQK(char * tmp);
char * GetYCQK(void);
void Add_Handl_Car_Information(int Index);
void Reduce_Handl_Car_Information(void);
struct Information_Node * Create_InforNode(void); 
void FreeG_Head_Information_Node(void);
#endif

